# Generated by Django 3.2 on 2021-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=200)),
                ('Message', models.TextField()),
                ('Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Current_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Web developer', max_length=50)),
                ('Started_at', models.CharField(default='Jan 2021', max_length=10)),
                ('Description', models.TextField(default='Lorem ipsum dolor sit amet. Praesentium magnam consectetur vel in deserunt aspernatur est reprehenderit sunt hic. Nulla tempora soluta ea et odio, unde doloremque repellendus iure, iste.')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='frontend developer / facebook', max_length=50)),
                ('Started_at', models.DateField()),
                ('Leave_at', models.DateField()),
                ('Description', models.TextField(default='Lorem ipsum dolor sit amet.')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(default='English', max_length=25)),
                ('Percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Lorem ipsum', max_length=25)),
                ('Title', models.CharField(default='Web developer', max_length=25)),
                ('Address', models.CharField(default='Sikkim India', max_length=50)),
                ('Email', models.EmailField(default='example@youremail.com', max_length=254)),
                ('Phone', models.CharField(default='+911234567890', max_length=15)),
                ('Image', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill', models.CharField(default='Python', max_length=50)),
                ('Percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.URLField()),
                ('Twitter', models.URLField()),
                ('Pintrest', models.URLField()),
                ('Instagram', models.URLField()),
                ('Linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='frontend developer / facebook', max_length=50)),
                ('Started_at', models.DateField()),
                ('Leave_at', models.DateField()),
                ('Description', models.TextField(default='Lorem ipsum dolor sit amet. Praesentium magnam consectetur vel in deserunt aspernatur est reprehenderit sunt hic. Nulla tempora soluta ea et odio, unde doloremque repellendus iure, iste.')),
            ],
        ),
    ]
