# Generated by Django 3.2 on 2021-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Time',
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='Image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
